### ISSUE TITLE
filename validation

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/transcription-review-backend#188]
this filename was created `tabconf/2021/lightning-dev-kit:-making-lightning-more-accessible-to-developers-matt-corallo-tabconf-2021.md`

colons, whitespaces, etc. should be validated and removed

**Comment by Extheoisah** [comment]
Is this in the loc of the transcript? I don't understand the file name issue

**Comment by nully0x** [comment]
@adamjonas is this also a reference to this? [https://github.com/bitcointranscripts/bitcointranscripts/pull/286](https://github.com/bitcointranscripts/bitcointranscripts/pull/286). 

We don't currently save file names to db, we only store the old content and the reviewed content. If we are looking at modifying the loc, that is doable from the BE before submitting a review.

cc @Extheoisah
