### ISSUE TITLE
self auth and admin auth middleware on update transcript

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcointranscripts/transcription-review-backend#189]
Add self and admin middleware auth on update transcript route.
i.e Only the reviewer who has an active review tied to a specific transcriptId can update said transcript. The only other exception is admin role.

**Comment by kouloumos** [comment]
This sounds related to [this issue](https://github.com/bitcointranscripts/transcription-review-front-end/issues/197) that I observed on the front-end.

**Comment by Extheoisah** [comment]
I dont understand why this is needed. Can you give a use case?

**Comment by Extheoisah** [comment]
We already have a check in the backend for whether the user updating the review is the one claimed the transcript
