### ISSUE TITLE
Route getUser by githubusername

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcointranscripts/transcription-review-backend#19]
Profiles in bitcoin transcripts are public.

Not sure how the implementation should be, we can currently get user reviews by id, maybe changing that to github username should suffice. Or we have a getUser by githubusername, get the id of that user then get reviews by that id. 
That seems like a longer route. 

@nassersaazi @adamjonas what are your thoughts on this?

**Comment by nassersaazi** [comment]
i don't object to the suggestion

**Comment by Extheoisah** [comment]
Is this issue still a WIP or its end user done? @Emmanuel-Develops

**Comment by Emmanuel-Develops** [comment]
> Is this issue still a WIP or its end user done? @Emmanuel-Develops

It has been completed
