### ISSUE TITLE
changing context for queueing transcript

### ISSUE THREAD

**Issue by nully0x** [bitcointranscripts/transcription-review-backend#243]
This issue focuses on reworking how we queue transcripts and changing to GitHub as the source for transcripts. 

Actions items:
- [x] create a webhook to check for appropriate source (via tstbtc) for transcripts and save the URL in db
- [x] create a new migration for transcript_url on the transcript table  and branch_url on the reviews table

**Comment by Extheoisah** [comment]
- [ ] parse the transcript content gotten from GitHub and create a new transcript to save to db
