### ISSUE TITLE
`/api/reviews/all` pagination issue 

### ISSUE THREAD

**Issue by kouloumos** [bitcointranscripts/transcription-review-backend#247]
While testing the new `status` parameter for the `/api/reviews/all` endpoint, I observed that it returns all the items, even if the pagination data at the beginning of the response says otherwise. 
At this time, this is only visible with `?status=expired` which is the only one with more than 10 items.

So, a request to `/api/reviews/all?status=expired&page=1` has this metadata for pagination:
```
"totalItems": 84,
"totalPages": 9,
"currentPage": 1,
"itemsPerPage": 10,
"hasNextPage": true,
"hasPreviousPage": false,
```

but returns all 84 items.

You can easily confirm this by testing through swagger, https://github.com/bitcointranscripts/transcription-review-backend/pull/246 make it easier by adding a couple missing params.

**Comment by nully0x** [comment]
@kouloumos I think this was attended. No? lemme know so I can fix up

**Comment by kouloumos** [comment]
I can still see the same issue that I am describing on both staging and production.
