### ISSUE TITLE
Implement Admin Endpoint for Resetting Transcript Claim

### ISSUE THREAD

**Issue by kouloumos** [bitcointranscripts/transcription-review-backend#249]
**Context**:
During testing phases, the need often arises to reset claimed transcripts manually. Presently, this involves navigating through the database to delete rows from the "reviews" table, adjust "status" and "claimBy" columns in the "transcripts" table, and additionally clear the relevant cache in Redis.

**Issue Description:**
To facilitate testing and streamline the resetting of claimed transcripts, it would be beneficial to introduce an admin endpoint. This endpoint would handle the necessary operations (database adjustments and cache clearing) in a simplified and automated manner.

**Benefits:**
- Efficiency: Simplifies and automates the manual steps required to reset claimed transcripts during testing.
- Accuracy: Reduces the margin for error in the manual database adjustments.
- Enhanced Testing Workflow: Allows easy resetting of claimed transcripts in staging and production environments without direct database access, facilitating smoother operations across different environments.

**Comment by nully0x** [comment]
This comes in handy, will create one.
