### ISSUE TITLE
Refactor process transcripts webhook

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcointranscripts/transcription-review-backend#303]
Skip processing invalid/unnecessary transcripts, and keep alerts to only necessary errors/alerts

- [x] process only `.md` files
- [x] skip `_index.md` files and its intl variants, e.g. `_index.es.md`
- [x] do not throw error for transcripts that do not need review
- [x] do not throw error if transcript needs review but already exists
- [x] Log in place of errors for these conditions

**Comment by kouloumos** [comment]
Solved by #304
