### ISSUE TITLE
lightning integration

### ISSUE THREAD

**Issue by Extheoisah** [bitcointranscripts/transcription-review-backend#91]
/api/withdraw/id=10&type=invoice&amount=100

add column:
1. settlementType: enum(INVOICE, LNURL) to transactions table
2. instantWithdraw: Boolean to userSettings table

renameColumn:
1. user table: authToken -> albyRefreshToken

create table:
1. userSettings 

Payment flow with Alby (for instant withdrawals):
1. user enables the instant withdraw setting on the frontend (setting and refreshToken is persisted in db)
2. once a user review is merged, our webhook generates an invoice for the user and pays the expected reward amount
3. we send an email to the user that the payment has been made for that review.

**Comment by nully0x** [comment]
@Extheoisah we can mark this close
